from time import sleep
def start():
    name = "kapil"
    print("\t\ti i i")
    sleep(1)
    print("\t\ti i i")
    sleep(1)
    print("\t:---------------:")
    print("\t:  Happy  +++++  :")
    sleep(1)
    print("\t +++++   Birthday  :")
    print(f"\t:  {name}  +++++  |  :")
    print("\t/_______________\ ")
    sleep(1)
    print("\t:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t--------------------")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  || ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  || ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  || ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  || ")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  || ")
    sleep(.5)
    print("Loading.........")
    sleep(1)
    print("A message to you.....")
    sleep(4)
    print("\t MAY GOD BLESS YOU.......")

a = input("1.Type : 'wish'\n2.PRESS 'ENTER' KEY\n(ELSE TYPE 'QUIT' TO QUIT)\n\n:").lower()
if (a == "wish"):
    start()
else:
    print("BYE!!!")